#!/usr/bin/env python3
"""Make a C header from a BDF bitmap font.

Usage: bdf2h.py IN.bdf OUT.h NAME FIRST LAST
Only fixed 8x16 cells are supported. Each glyph becomes 16 bytes, one byte
for each row, the high bit on the left.
"""
import sys

def main():
    src, dst, name, first, last = sys.argv[1], sys.argv[2], sys.argv[3], int(sys.argv[4]), int(sys.argv[5])
    glyphs, cp, bbx, rows, in_bitmap = {}, None, None, [], False

    for line in open(src, encoding='latin-1'):
        line = line.strip()
        if line.startswith('ENCODING'):
            cp = int(line.split()[1])
        elif line.startswith('BBX'):
            bbx = tuple(int(v) for v in line.split()[1:5])
        elif line == 'BITMAP':
            in_bitmap, rows = True, []
        elif line == 'ENDCHAR':
            in_bitmap = False
            if cp is not None and first <= cp <= last:
                if bbx != (8, 16, 0, -4):
                    raise SystemExit('glyph %d has BBX %s, want (8, 16, 0, -4)' % (cp, bbx))
                if len(rows) != 16:
                    raise SystemExit('glyph %d has %d rows, want 16' % (cp, len(rows)))
                glyphs[cp] = rows
        elif in_bitmap:
            rows.append(int(line, 16) & 0xff)

    missing = [c for c in range(first, last + 1) if c not in glyphs]
    if missing:
        raise SystemExit('missing code points: %s' % missing)

    out = ['/* Generated by tools/bdf2h.py from %s. Do not edit. */' % src.split('/')[-1],
           '/* Spleen, Copyright (c) 2018-2024 Frederic Cambus, BSD-2-Clause. */',
           '#ifndef WWEFT_%s_H' % name.upper(),
           '#define WWEFT_%s_H' % name.upper(),
           '',
           '#define %s_WIDTH  8' % name.upper(),
           '#define %s_HEIGHT 16' % name.upper(),
           '#define %s_FIRST  %d' % (name.upper(), first),
           '#define %s_LAST   %d' % (name.upper(), last),
           '',
           'static const unsigned char %s[%d][16] = {' % (name, last - first + 1)]
    for c in range(first, last + 1):
        body = ', '.join('0x%02x' % b for b in glyphs[c])
        out.append('\t{ %s },  /* %d */' % (body, c))
    out += ['};', '', '#endif', '']
    open(dst, 'w').write('\n'.join(out))
    print('%s: %d glyphs' % (dst, last - first + 1))

main()
