#!/bin/sh
# Turn text files into one C string constant.
#   tools/txt2h.sh NAME FILE...    > out.h
set -eu

name=$1
shift

printf '/* Generated by tools/txt2h.sh. Do not edit. */\n'
printf 'static const char %s[] =\n' "$name"
sed -e 's/\\/\\\\/g' -e 's/"/\\"/g' -e 's/^/\t"/' -e 's/$/\\n"/' "$@"
printf ';\n'
